### ISSUE TITLE
Print Arabic characters 

### ISSUE THREAD

**Issue by safanmomin** [don/BluetoothSerial#241] opened 2016-06-21 09:42 UTC
Printing arabic characters doesn't work. How can I make it work?
 I'm using the code like this;
bluetoothSerial.write("تجريب", function(){alert('success')}, function(){alert('error')});
instead of printing out the arabic it prints out some random characters.

**Comment by don** [comment] 2016-06-23 02:04
This is a duplicate of #240

**Closed by don** 2016-06-23 02:04 UTC
