### ISSUE TITLE
Android: bluetoothSerial.connect does not fire callbacks

### ISSUE THREAD

**Issue by AsreshSharma** [don/BluetoothSerial#325] opened 2017-08-09 09:29 UTC
08-09 14:53:43.517 21574-21574/io.ionic.starter D/SystemWebChromeClient: file:///android_asset/www/build/main.js: Line 72 : uniqueArray is: [{"name":"GT-S7582","address":"34:BE:00:C4:0D:11","id":"34:BE:00:C4:0D:11","class":524}]
08-09 14:53:43.517 21574-21574/io.ionic.starter I/chromium: [INFO:CONSOLE(72)] "uniqueArray is: [{"name":"GT-S7582","address":"34:BE:00:C4:0D:11","id":"34:BE:00:C4:0D:11","class":524}]", source: file:///android_asset/www/build/main.js (72)
08-09 14:53:43.517 21574-21574/io.ionic.starter D/SystemWebChromeClient: file:///android_asset/www/build/main.js: Line 73 : [object Object]
08-09 14:53:43.517 21574-21574/io.ionic.starter I/chromium: [INFO:CONSOLE(73)] "[object Object]", source: file:///android_asset/www/build/main.js (73)
08-09 14:53:49.303 21574-21574/io.ionic.starter D/webcore: WebContentsImpl::Send 
08-09 14:53:52.586 21574-21574/io.ionic.starter D/webcore: WebContentsImpl::Send 
08-09 14:53:52.686 21574-21655/io.ionic.starter D/BluetoothSerial: action = connect
08-09 14:53:52.686 21574-21655/io.ionic.starter D/BluetoothSerialService: connect to: 34:BE:00:C4:0D:11
08-09 14:53:52.696 21574-21655/io.ionic.starter D/BluetoothSerialService: setState() 0 -> 2
08-09 14:53:52.696 21574-21655/io.ionic.starter I/BluetoothSerial: MESSAGE_STATE_CHANGE: 2
08-09 14:53:52.696 21574-21655/io.ionic.starter I/BluetoothSerial: BluetoothSerialService.STATE_CONNECTING
08-09 14:53:52.696 21574-27387/io.ionic.starter I/BluetoothSerialService: BEGIN mConnectThread SocketType:Secure
08-09 14:53:52.706 21574-27387/io.ionic.starter I/BluetoothSerialService: Connecting to socket...
08-09 14:53:52.706 21574-27387/io.ionic.starter W/BluetoothAdapter: getBluetoothService() called with no BluetoothManagerCallback
08-09 14:53:55.369 21574-27387/io.ionic.starter E/BluetoothSerialService: java.io.IOException: read failed, socket might closed or timeout, read ret: -1
08-09 14:53:55.369 21574-27387/io.ionic.starter I/BluetoothSerialService: Trying fallback...
08-09 14:53:55.369 21574-27387/io.ionic.starter W/BluetoothAdapter: getBluetoothService() called with no BluetoothManagerCallback
08-09 14:53:56.340 21574-21574/io.ionic.starter D/CordovaActivity: Paused the activity.
08-09 14:54:26.279 21574-27387/io.ionic.starter E/BluetoothSerialService: Couldn't establish a Bluetooth connection.
08-09 14:54:26.279 21574-27387/io.ionic.starter D/BluetoothSerialService: start
08-09 14:54:26.279 21574-27387/io.ionic.starter D/BluetoothSerialService: setState() 2 -> 0
08-09 14:54:26.279 21574-21655/io.ionic.starter I/BluetoothSerial: MESSAGE_STATE_CHANGE: 0
08-09 14:54:26.279 21574-21655/io.ionic.starter I/BluetoothSerial: BluetoothSerialService.STATE_NONE
08-09 14:54:26.299 21574-21574/io.ionic.starter D/SystemWebChromeClient: file:///android_asset/www/build/main.js: Line 112 : Failure Data : "Unable to connect to device"
08-09 14:54:26.299 21574-21574/io.ionic.starter I/chromium: [INFO:CONSOLE(112)] "Failure Data : "Unable to connect to device"", source: file:///android_asset/www/build/main.js (112)
08-09 14:54:26.329 21574-21655/io.ionic.starter D/BluetoothSerial: action = disconnect
08-09 14:54:26.329 21574-21655/io.ionic.starter D/BluetoothSerialService: stop
08-09 14:54:26.329 21574-21655/io.ionic.starter D/BluetoothSerialService: setState() 0 -> 0
08-09 14:54:26.329 21574-21655/io.ionic.starter I/BluetoothSerial: MESSAGE_STATE_CHANGE: 0
08-09 14:54:26.329 21574-21655/io.ionic.starter I/BluetoothSerial: BluetoothSerialService.STATE_NONE
08-09 14:54:26.359 21574-21574/io.ionic.starter D/CordovaActivity: Resumed the activity.
08-09 14:54:26.359 21574-21574/io.ionic.starter V/Activity: calling onResume for activity: io.ionic.starter

**Comment by don** [comment] 2017-08-18 16:41
Duplicate of #308

**Closed by don** 2017-08-18 16:41 UTC
