### ISSUE TITLE
Multiple connections using Android device

### ISSUE THREAD

**Issue by meetsagarlandge25** [don/BluetoothSerial#334] opened 2017-09-17 06:05 UTC
Hi Don, greetings
I am fairly new to BT development. I have a college assignment , the requirement is I need to connect to multiple windows PC at the same time. 
Currently I am able to establish communication with multiple PCs but I can only remain connected to one PC at a time. But I need to maintain and receive data from multiple PCs at same time. I am using classic Bluetooth. Please suggest changes on my PC side code and Android  code.

**Comment by don** [comment] 2017-10-23 16:47
Duplicate of #58. 

Some people kludge this by installing multiple instances of the plugin. See #58 for more details.

My Bluetooth Low Energy plugin supports multiple simultaneous connections. https://github.com/don/cordova-plugin-ble-central

**Closed by don** 2017-10-23 16:47 UTC
