### ISSUE TITLE
Android to android bluetooth communication

### ISSUE THREAD

**Issue by RobinDesir** [don/BluetoothSerial#192] opened 2016-01-14 17:27 UTC
Hey Don, 

Is it possible to communicate with another Android device ? I keep getting the "Unable to connect to device" error ... 

Thx in advance for your answer, 
Robin.

**Comment by RobinDesir** [comment] 2016-01-15 16:53
I read that it was because Android to Android communication via this plugin wasn't supported in another issue, is it still true ?

**Comment by don** [comment] 2016-01-15 16:53
@RobinDesir Android to Android isn't supported by default. If you see Issue #50 some people have android-to-android working in forks of the plugin.

Ideally once someone has this working and tested, they'll submit a pull request so it can be part of the library.

Closing this as a duplicate of #50

**Closed by don** 2016-01-15 16:53 UTC

**Comment by RobinDesir** [comment] 2016-01-15 16:56
Thx for your quick answer don.
