### ISSUE TITLE
Connection to Adafruit Flora Bluefruit LE failing

### ISSUE THREAD

**Issue by zpeterg** [don/BluetoothSerial#185] opened 2016-01-10 22:01 UTC
I am unable to connect to a Flora 2 via Bluefruit LE (flora edition, which is a version of Adafruit Friend). I am using Adafruit's BleUart example (https://learn.adafruit.com/adafruit-flora-bluefruit-le/bleuart) and successfuly communicating with their Bluefruit LE Android app, but I cannot connect with either bluetoothSerial.connect or bluetoothSerial.connectInsecure. I am using the MAC address returned by bluetoothSerial.list. Here is the result of .list:
: Object
address: "EC:FA:F4:44:31:79"
class: 7936
id: "EC:FA:F4:44:31:79"
name: "Adafruit Bluefruit LE"
__proto__: Object
length: 2
__proto__: Array[0]

bluetoothSerial.connectInsecure('EC:FA:F4:44:31:79', function(){console.log('connected'); }, function(){console.log('no connected'); });

I am using a MotoX 1st Gen running Android 4.4.4.

Any help would be much appreciated as I have gone round-and-round on this with no success!

**Comment by don** [comment] 2016-01-10 23:28
duplicate of #186

**Closed by don** 2016-01-10 23:28 UTC
